PBP-490 - Redesign The General Layout and Complete Order List
deliveryhero/pd-billing-view pull request #12
Opened 2023-03-27 22:55 UTC by tejazz

## Jira:

[PBP-490](https://jira.deliveryhero.com/browse/PBP-490)

## Description

(Please add description about the change)

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring change (no changes in functionality, e.g: cleaning up code)
- [ ] This change requires a documentation update

## Screenshot

(Add screenshot if relevant to the change)

2023-03-30 15:28 UTC, sergiomendoncadh requested changes
Code looks good in general, just requested some small changes.

2023-03-30 15:28 UTC, sergiomendoncadh commented on src/modules/components/FilterMenu/FilterMenu.tsx
> +    }),
I see repeated code here. Could you extract this object creation to a separated function?

2023-03-30 15:28 UTC, sergiomendoncadh commented on src/modules/components/OrderList/OrderList.tsx
> +                                            <TableCell contentAlignX='center'>{order?.orderUpdatedAt && new Date(order?.orderUpdatedAt).toISOString()}</TableCell>
Could we use a better date format here? maybe `DD/MM/YYYT HH:mm:ss`

2023-03-30 15:28 UTC, sergiomendoncadh commented on src/utils/constants.ts
> +    'cancelled': 'denied',
Wouldn't be better to differentiate cancelled from failed? This way cancelled orders look like errors, which they're not.

2023-03-30 15:39 UTC, tejazz commented on src/utils/constants.ts
> +    'cancelled': 'denied',
Noted. I will add a different format.

2023-03-31 12:14 UTC, tejazz commented on src/modules/components/FilterMenu/FilterMenu.tsx
> +    }),
There is no clean way to extract this out since `formatDateTime` already invokes the abstracted function `format` from `date-fns`.

2023-04-03 10:10 UTC, sergiomendoncadh requested changes
Just a small change request about the order_placed_at date.

2023-04-03 10:10 UTC, sergiomendoncadh commented on src/modules/components/OrderList/OrderList.tsx
> +                                            <TableCell contentAlignX='center'>{order?.orderPlacedAt && new Date(order?.orderPlacedAt).toLocaleString()}</TableCell>
As discussed, as we don't have the time information for this field, we should show only the date, without time.

2023-04-03 10:10 UTC, sergiomendoncadh commented on src/utils/helper.ts
>    const orderCodePattern = new RegExp('[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}', 'g');
should we also consider the dine in pattern here?

2023-04-03 10:12 UTC, sergiomendoncadh commented
Another thing that I've obeserved, the order code filter is not being cleared when we change the country and I believe it should.

2023-04-03 10:24 UTC, tejazz commented on src/utils/helper.ts
>    const orderCodePattern = new RegExp('[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}', 'g');
We should. We are not using this at present. But I will add it to make sure we don't miss this.

2023-04-03 12:02 UTC, sergiomendoncadh approved these changes
LGTM

2023-04-03 12:28 UTC, merged